ID_pt_bins_inc_eta:
  # Settings for histogram creation
  name: 'ID_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28'
  probe: 'id_p'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Medium ID"
  y_range: [0.8,1.0]
  ratio_y_range: [0.9,1.1]

ID_pt_eta_bins:
  name: 'ID_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28'
  probe: 'id_p'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Medium ID"
  y_range: [0.8,1.0]
  ratio_y_range: [0.9,1.1]

Iso_pt_bins_inc_eta:
  name: 'Iso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && id_p'
  probe: 'iso_p < 0.15'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} < 0.15"
  y_range: [0.6,1.0]
  ratio_y_range: [0.9,1.1]

Iso_pt_eta_bins:
  name: 'Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && id_p'
  probe: 'iso_p < 0.15'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} < 0.15"
  y_range: [0.6,1.0]
  ratio_y_range: [0.9,1.1]

AIso1_pt_bins_inc_eta:
  name: 'AIso1_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && id_p'
  probe: 'iso_p >= 0.15 && iso_p < 0.25'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} #in [0.15,0.25]"
  y_range: [0.6,1.0]
  ratio_y_range: [0.9,1.1]

AIso1_pt_eta_bins:
  name: 'AIso1_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && id_p'
  probe: 'iso_p >= 0.15 && iso_p < 0.25'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} #in [0.15,0.25]"
  y_range: [0.6,1.0]
  ratio_y_range: [0.9,1.1]

AIso2_pt_bins_inc_eta:
  name: 'AIso2_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && id_p'
  probe: 'iso_p >= 0.25 && iso_p < 0.50'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} #in [0.25,0.50]"
  y_range: [0.6,1.0]
  ratio_y_range: [0.9,1.1]

AIso2_pt_eta_bins:
  name: 'AIso2_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && id_p'
  probe: 'iso_p >= 0.25 && iso_p < 0.50'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 22., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} #in [0.25,0.50]"
  y_range: [0.6,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu27_pt_eta_bins:
  name: 'Trg_IsoMu27_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p < 0.15 && id_p'
  probe: 'trg_p_IsoMu27'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu27"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu27_AIso1_pt_bins_inc_eta:  
  name: 'Trg_IsoMu27_AIso1_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p >= 0.15 && iso_p < 0.25 && id_p'
  probe: 'trg_p_IsoMu27'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu27, Iso_{rel} #in [0.15,0.25]"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu27_AIso2_pt_bins_inc_eta:
  name: 'Trg_IsoMu27_AIso2_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p >= 0.25 && iso_p < 0.50 && id_p'
  probe: 'trg_p_IsoMu27'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu27, Iso_{rel} #in [0.15,0.25]"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu24_pt_eta_bins:
  name: 'Trg_IsoMu24_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p < 0.15 && id_p'
  probe: 'trg_p_IsoMu24'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu24"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu24_AIso1_pt_bins_inc_eta:  
  name: 'Trg_IsoMu24_AIso1_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p >= 0.15 && iso_p < 0.25 && id_p'
  probe: 'trg_p_IsoMu24'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu24, Iso_{rel} #in [0.15,0.25]"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu24_AIso2_pt_bins_inc_eta:  
  name: 'Trg_IsoMu24_AIso2_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p >= 0.25 && iso_p < 0.50 && id_p'
  probe: 'trg_p_IsoMu24'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE:  "Trg IsoMu24, Iso_{rel} #in [0.25,0.5]"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu27_or_IsoMu24_pt_eta_bins:  
  name: 'Trg_IsoMu27_or_IsoMu24_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p < 0.15 && id_p'
  probe: '(trg_p_IsoMu27|| trg_p_IsoMu24)'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu24 or IsoMu27"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu27_or_IsoMu24_AIso1_pt_bins_inc_eta:  
  name: 'Trg_IsoMu27_or_IsoMu24_AIso1_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p >= 0.15 && iso_p < 0.25 && id_p'
  probe: '(trg_p_IsoMu27|| trg_p_IsoMu24)'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu24 or IsoMu27, Iso_{rel} #in [0.15,0.25]"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]

Trg_IsoMu27_or_IsoMu24_AIso2_pt_bins_inc_eta:  
  name: 'Trg_IsoMu27_or_IsoMu24_AIso2_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_IsoMu27 && pt_t > 28 && iso_p >= 0.25 && iso_p < 0.50 && id_p'
  probe: '(trg_p_IsoMu27|| trg_p_IsoMu24)'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 38., 40., 45., 50., 60., 80., 100., 200., 1000.]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg IsoMu24 or IsoMu27, Iso_{rel} #in [0.25,0.5]"
  y_range: [0.0,1.0]
  ratio_y_range: [0.9,1.1]
