# styles_pt.py

def default_pt_plot_style():
    return {
        "xscale": "linear",
        "broken_axis": True,
        "x_lin_min": 10,
        "x_lin_max": 40,
        "x_log_min": 40,
        "x_log_max": 200,
        "broken_axis_gap": 0.000,
        "xlabel": r"$p_T$ [GeV]",
        "ylabel": "Scale Factor",
        "title": r"",
        "color": "C0",
        "marker": "o",
        "figsize": (15, 8),
        "label_size": 22,
        "tick_size": 17,
        "title_size_main": 20,
        "title_size": 15,
        "cms_label": "Preliminary",
        "lumi": 59.8,
        #"com": 13,
        "bin_edge_color": "darkgreen",
        "bin_edge_height_frac": 0.03,
        "point_size": 6,
        "grid_style": {"linestyle": "--", "linewidth": 0.8, "alpha": 0.3},
        "spine_width": 0.8,
        "tick_direction": "in",
        "tick_length": 4,
        "legend_frame_alpha": 0.25,
        "legend_frame_color": "black",
        "stat_error_color": "black",
        "total_error_color": "red", 
        "stat_error_width": 4.0,
        "total_error_width": 1.0,
        "best_model_color": "blue",
        "best_model_alpha": 0.3,
        "best_model_edge_color": "darkorange", 
        "best_model_edge_width": 1.0,
    }
