---
tauId_wps_mva: &mva_tau
    vloose: "byVLooseIsolationMVArun2017v2DBoldDMwLT2017_p"
    loose: "byLooseIsolationMVArun2017v2DBoldDMwLT2017_p"
    medium: "byMediumIsolationMVArun2017v2DBoldDMwLT2017_p"
    tight: "byTightIsolationMVArun2017v2DBoldDMwLT2017_p"
    vtight: "byVTightIsolationMVArun2017v2DBoldDMwLT2017_p"
    vvtight: "byVVTightIsolationMVArun2017v2DBoldDMwLT2017_p"

tauId_wps_deeptau: &deep_tau
    vvvloose: "byVVVLooseDeepTau2017v2p1VSjet_p"
    vvloose: "byVVLooseDeepTau2017v2p1VSjet_p"
    vloose: "byVLooseDeepTau2017v2p1VSjet_p"
    loose: "byLooseDeepTau2017v2p1VSjet_p"
    medium: "byMediumDeepTau2017v2p1VSjet_p"
    tight: "byTightDeepTau2017v2p1VSjet_p"
    vtight: "byVTightDeepTau2017v2p1VSjet_p"
    vvtight: "byVVTightDeepTau2017v2p1VSjet_p"

baseline_selection_mva: &baseline_selection_mva
    tag_trg: "trg_singlemuon_27"
    probe_eta: "abs(eta_p) < 2.1"
    m_vis: "40. < m_ll && m_ll < 80."
    mT: "mt_t < 30"
    decayModeFinding: "decayModeFinding_p > 0.5"
    antiMu: "againstMuonTight3_p > 0.5"
    antiE: "againstElectronVLooseMVA6_p > 0.5"
    # "(-1.)*(isOS==false)"

baseline_selection_mva_et: &baseline_selection_mva_et
    tag_trg: "trg_singleelectron_35"
    probe_eta: "abs(eta_p) < 2.1"
    m_vis: "40. < m_ll && m_ll < 80."
    mT: "mt_t < 30"
    decayModeFinding: "decayModeFinding_p > 0.5"
    antiMu: "againstMuonTight3_p > 0.5"
    antiE: "againstElectronTightMVA6_p > 0.5"
    # - "(-1.)*(isOS==false)"

baseline_selection_deep: &baseline_selection_deep
    <<: *baseline_selection_mva
    decayModeFinding: "decayModeFindingNewDMs_p > 0.5"
    antiMu: "byLooseDeepTau2017v2p1VSmu_p > 0.5"
    antiE: "byVVLooseDeepTau2017v2p1VSe_p > 0.5"
    # "(-1.)*(isOS==false)"

baseline_selection_deep_et: &baseline_selection_deep_et
    <<: *baseline_selection_mva_et
    decayModeFinding: "decayModeFinding_p > 0.5"
    antiMu: "byVLooseDeepTau2017v2p1VSmu_p > 0.5"
    antiE: "byMediumDeepTau2017v2p1VSe_p > 0.5"
    # - "(-1.)*(isOS==false)"

tauId_wps: &tauId_wps
    MVAv2: *mva_tau
    DeepTau: *deep_tau

baseline_selection: &baseline_selection
    MVAv2: *baseline_selection_mva
    DeepTau: *baseline_selection_deep

baseline_selection_et: &baseline_selection_et
    MVAv2: *baseline_selection_mva_et
    DeepTau: *baseline_selection_deep_et

trigger_dict_2016: &trgs_2016
    etau: "trg_crossmuon_mu19tau20_singlel1"
    mutau: "trg_crossmuon_mu19tau20_singlel1||trg_crossmuon_mu19tau20"
    tau35: "trg_monitor_mu19tau35_mediso"
    # Tau35: "trg_monitor_mu24tau35_medcombiso"
    ditau: "trg_monitor_mu19tau35_mediso||trg_monitor_mu19tau35_medcombiso"
    TauLead: "trg_singletau_leading"
    TauTrail: "trg_singletau_trailing"

trigger_dict_2017: &trgs_2017
    etau: "trg_monitor_mu20tau27"
    mutau: "trg_crossmuon_mu20tau27"
    tau35: "trg_monitor_mu24tau35_tight_tightID"
    medtau40: "trg_monitor_mu24tau35_medium_tightID"
    # MedTau40: "trg_monitor_mu24tau40_mediso_tightid"
    tighttau40: "trg_monitor_mu24tau35_tight"
    # TightTau40: "trg_monitor_mu24tau40_tightiso"
    # ditau: "trg_monitor_mu24tau35_tight_tightID||trg_monitor_mu24tau40_medium_tightID||trg_monitor_mu24tau40_tight"
    ditau: "trg_monitor_mu24tau35_tightiso_tightid||trg_monitor_mu24tau40_mediso_tightid||trg_monitor_mu24tau40_tightiso"
    ditauvbf: "trg_monitor_mu24tau20_looseiso_reg"
    ditauvbf_glob: "trg_monitor_mu24tau20_looseiso"
    ditauvbf_comp: "trg_monitor_mu24tau20_looseiso_comp"
    TauLead: "trg_singletau_leading"
    TauTrail: "trg_singletau_trailing"

trigger_dict_2018: &trgs_2018
    etau: "trg_monitor_mu20tau27_hps"
    mutau: "trg_crossmuon_mu20tau27_hps"
    hpstau35: "trg_monitor_mu24tau35_mediso_hps"
    ditau: "trg_monitor_mu24tau35_mediso_hps"
    ditauvbf: "trg_monitor_mu27tau20_hps"
    TauLead: "trg_singletau_leading"
    TauTrail: "trg_singletau_trailing"

2016:
    tree_name: "mt/ntuple"
    tree_name_et: "et/ntuple"
    baseline_selection: *baseline_selection
    baseline_selection_et: *baseline_selection_et
    tauId_wps: *tauId_wps
    trigger_dict:
        MC: *trgs_2016
        DATA:
            <<: *trgs_2016
            etau: "(trg_crossmuon_mu19tau20_singlel1&&(run<276215))||(trg_crossmuon_mu19tau20&&(run>=276215&&run<278270))||(trg_monitor_mu19tau30&&(run>=278270))"
            ditau: "(trg_monitor_mu19tau35_mediso&&(run<=280385))||(trg_monitor_mu19tau35_medcombiso&&(run>=280919))"
        EMB: *trgs_2016
    trigger_dict_et:
        MC:
            etau: "trg_crosselectron_ele24tau20_singlel1"
        DATA:
            etau: "(trg_crosselectron_ele24tau20_singlel1&&(run<276215))||(trg_crosselectron_ele24tau20&&(run>=276215&&run<278270))||(trg_crosselectron_ele24tau30&&(run>=278270))"
        EMB:
            etau: "trg_crosselectron_ele24tau20_singlel1"
    file_dict:
        MC: "DYJetsToLLM50*Summer16*"
        DATA: "SingleMuon*Run2016*"
        EMB: "Embedding2016*MuTau*"
    file_dict_et:
        MC: "DYJetsToLLM50*Summer16*"
        DATA: "SingleElectron*Run2016*"
        EMB: "Embedding2016*ElTau*"
    etaphi_cats:
        Average:
            - "true"
        Barrel:
            - "true"
        Endcap:
            - "true"
2017:
    tree_name: "mt/ntuple"
    tree_name_et: "et/ntuple"
    baseline_selection: *baseline_selection
    baseline_selection_et: *baseline_selection_et
    tauId_wps: *tauId_wps
    trigger_dict:
        MC: *trgs_2017
        DATA: *trgs_2017
        EMB: *trgs_2017
    trigger_dict_et:
        MC:
            etau: "trg_crosselectron_ele24tau30"
        DATA:
            etau: "trg_crosselectron_ele24tau30"
        EMB:
            etau: "trg_crosselectron_ele24tau30"
    file_dict:
        # MC: "DYJetsToLLM50*Fall17*"
        MC: "VBFHToTauTau*Summer17*"
        DATA: "SingleMuon*Run2017D*"
        EMB: "Embedding2017*MuTau*"
    file_dict_et:
        MC: "DYJetsToLLM50*Fall17*"
        DATA: "SingleElectron*Run2017*"
        EMB: "Embedding2017*ElTau*"
    etaphi_cats:
        Average:
            - "true"
        Endcap:
            - "abs(eta_p) > 1.5"
        NonPixelProblemBarrel:
            - "abs(eta_p) < 1.5"
            - "(phi_p < 2.8 || eta_p <= 0)"
        PixelProblemBarrel:
            - "eta_p > 0 && eta_p < 1.5"
            - "phi_p > 2.8"
2018:
    tree_name: "mt/ntuple"
    tree_name_et: "et/ntuple"
    baseline_selection: *baseline_selection
    baseline_selection_et: *baseline_selection_et
    tauId_wps: *tauId_wps
    trigger_dict:
        MC: *trgs_2018
        DATA:
            <<: *trgs_2018
            tau35: "trg_monitor_mu24tau35_tigthiso_tightid"
            medtau40: "trg_monitor_mu24tau40_mediso_tightid"
            tighttau40: "trg_monitor_mu24tau40_tightiso"
            ditau: "(trg_monitor_mu24tau35_mediso_hps&&(run>=317509))||((trg_monitor_mu24tau35_tightiso_tightid||trg_monitor_mu24tau40_mediso_tightid||trg_monitor_mu24tau40_tightiso)&&(run<317509))"
            mutau: "(trg_crossmuon_mu20tau27_hps&&(run>=317509))||(trg_crossmuon_mu20tau27&&(run<317509))"
            etau: "(trg_monitor_mu20tau27_hps&&(run>=317509))||(trg_monitor_mu20tau27&&(run<317509))"
            ditauvbf: "(trg_monitor_mu27tau20&&(run<317509))||(trg_monitor_mu27tau20_hps&&(run>=317509))"
        EMB: *trgs_2018
    trigger_dict_et:
        MC:
            etau: "trg_crosselectron_ele24tau30_hps"
        DATA:
            etau: "(trg_crosselectron_ele24tau30_hps&&(run>=317509))||(trg_crosselectron_ele24tau30&&(run<317509))"
        EMB:
            etau: "trg_crosselectron_ele24tau30_hps"
    file_dict:
        MC: "DYJetsToLLM50*Autumn18*"
        DATA: "SingleMuon*Run2018*"
        EMB: "Embedding2018*MuTau*"
    file_dict_et:
        MC: "DYJetsToLLM50*Autumn18*"
        DATA: "EGamma*Run2018*"
        EMB: "Embedding2018*ElTau*"
    etaphi_cats:
        Average:
            - "true"
        Barrel:
            - "abs(eta_p) < 1.5"
        NonHCALProblemEndcap:
            - "(((eta_p > -2.1 && eta_p < -1.5) && (phi_p > -3.2  && phi_p < -1.6)) || ((eta_p > -2.1 && eta_p < -1.5) &&  (phi_p > -0.8  && phi_p < 3.2)) || ( eta_p > 1.5 && eta_p < 2.1))"
        HCALProblemEndcap:
            - "(eta_p > -2.1 && eta_p < -1.5)"
            - "(phi_p > -1.6 && phi_p < -0.8)"
...
