ID90_pt_bins_inc_eta:
  name: 'ID90_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t'
  probe: 'id_90_p'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "MVA ID 17 WP90"
  y_range: [0.0,1.05]
  ratio_y_range: [0.6,1.4]

ID80_pt_eta_bins:
  name: 'ID80_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t'
  probe: 'id_80_p'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "MVA ID 17 WP80"
  y_range: [0.0,1.05]
  ratio_y_range: [0.6,1.4]

ID90_pt_eta_bins:
  name: 'ID90_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t'
  probe: 'id_90_p '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "MVA ID 17 WP90"
  y_range: [0.5,1.05]
  ratio_y_range: [0.8,1.2]

Iso_pt_bins_inc_eta:
  name: 'Iso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t && id_90_p'
  probe: 'iso_p < 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} < 0.15"
  y_range: [0.8,1.0]
  ratio_y_range: [0.9,1.1]

Iso_pt_eta_bins:
  name: 'Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t && id_90_p'
  probe: 'iso_p < 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} < 0.15"
  y_range: [0.8,1.0]
  ratio_y_range: [0.9,1.1]

AIso_pt_bins_inc_eta:
  name: 'AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t && id_90_p'
  probe: 'iso_p >= 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} > 0.15"
  y_range: [0.0,1.0]
  ratio_y_range: [0.6,1.4]

AIso_pt_eta_bins:
  name: 'AIso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t && id_90_p'
  probe: 'iso_p >= 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} > 0.15"
  y_range: [0.0,1.0]
  ratio_y_range: [0.6,1.4]

Trg_Iso_pt_bins_inc_eta:
  name: 'Trg_Iso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele27 || trg_p_Ele35 || trg_p_Ele32|| trg_p_Ele32_fb)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele27 or Ele35 or Ele32"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg_Iso_pt_eta_bins:
  name: 'Trg_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele27 || trg_p_Ele35 || trg_p_Ele32|| trg_p_Ele32_fb)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||32||32fb||35)"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg_AIso_pt_bins_inc_eta:
  name: 'Trg_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele27 || trg_p_Ele35 || trg_p_Ele32|| trg_p_Ele32_fb)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||32||32fb||35), Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg27_Iso_pt_eta_bins:
  name: 'Trg27_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele27)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele27"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]
  
Trg27_AIso_pt_bins_inc_eta:
  name: 'Trg27_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele27)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele27, Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg32_Iso_pt_eta_bins:
  name: 'Trg32_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele32)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele32"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg32_AIso_pt_bins_inc_eta:
  name: 'Trg32_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele32)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele32, Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg32_fb_Iso_pt_eta_bins:
  name: 'Trg32_fb_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele32_fb)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele32_fallback"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg32_fb_AIso_pt_bins_inc_eta:
  name: 'Trg32_fb_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele32_fb)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele32_fallback, Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg35_Iso_pt_eta_bins:
  name: 'Trg35_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele35)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele35"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg35_AIso_pt_bins_inc_eta:
  name: 'Trg35_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele35)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele35, Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg27_or_Trg32_Iso_pt_eta_bins:
  name: 'Trg27_or_Trg32_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele27 || trg_p_Ele32)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||32)"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg27_or_Trg32_AIso_pt_bins_inc_eta:
  name: 'Trg27_or_Trg32_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele27 || trg_p_Ele32)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||32), Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg27_or_Trg35_Iso_pt_eta_bins:
  name: 'Trg27_or_Trg35_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele35 || trg_p_Ele27)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||35)"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg27_or_Trg35_AIso_pt_bins_inc_eta:
  name: 'Trg27_or_Trg35_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele35 || trg_p_Ele27)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||35), Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg27_or_Trg32_or_Trg35_Iso_pt_eta_bins:
  name: 'Trg27_or_Trg32_or_Trg35_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele35 || trg_p_Ele32 || trg_p_Ele27)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||32||35)"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg27_or_Trg32_or_Trg35_AIso_pt_bins_inc_eta:
  name: 'Trg27_or_Trg32_or_Trg35_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele35 || trg_p_Ele32 || trg_p_Ele27)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(27||32||35), Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg32_or_Trg35_Iso_pt_eta_bins:
  name: 'Trg32_or_Trg35_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: '(trg_p_Ele32 || trg_p_Ele35)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(32||35)"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]

Trg32_or_Trg35_AIso_pt_bins_inc_eta:
  name: 'Trg32_or_Trg35_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele35 && pt_t >= 36 && id_90_t && iso_p >= 0.15 && id_90_p'
  probe: '(trg_p_Ele32 || trg_p_Ele35)'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele(32||35), Iso_{rel} > 0.15"
  y_range: [0.0,1.1]
  ratio_y_range: [0.1,1.9]
