Ele24_Iso_pt_eta_bins:
  name: 'Ele24_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele27 && pt_t >= 28 && iso_p < 0.15  && id_90_p && id_90_t && isAntiL1TauMatched_trg_p_ele24tau30>0.5'
  probe: 'trg_p_ele24tau30'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 21.,22.,23.,24., 25.,26.,27.,28.,29.,  30., 35., 40.,  50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele24Tau30 electron leg"
  y_range: [0.0,1.1]
  ratio_y_range: [0.5,1.5]

Ele24_Iso_pt_bins_inc_eta:
  name: 'Ele24_Iso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele27 && pt_t >=28 && iso_p < 0.15 && id_90_p && id_90_t && isAntiL1TauMatched_trg_p_ele24tau30>0.5'
  probe: 'trg_p_ele24tau30'
  binvar_x: 'pt_p'
  bins_x: [10., 20.,21.,22.,23.,24., 25., 26., 27., 28., 29., 30., 35., 40.,  50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele24Tau30 electron leg"
  y_range: [0.0,1.1]
  ratio_y_range: [0.5,1.5]
