ID90_pt_bins_inc_eta:
  name: 'ID90_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 && id_90_t'
  probe: 'id_90_p'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "MVA ID 17 WP90"
  y_range: [0.5,1.05]
  ratio_y_range: [0.8,1.2]

ID80_pt_eta_bins:
  name: 'ID80_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 && id_90_t'
  probe: 'id_80_p'
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "MVA ID 17 WP80"
  y_range: [0.5,1.05]
  ratio_y_range: [0.8,1.2]

ID90_pt_eta_bins:
  name: 'ID90_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 && id_90_t'
  probe: 'id_90_p '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "MVA ID 17 WP90"
  y_range: [0.5,1.05]
  ratio_y_range: [0.8,1.2]

Iso_pt_bins_inc_eta:
  name: 'Iso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 && id_90_t && id_90_p'
  probe: 'iso_p < 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} < 0.15"
  y_range: [0.6,1.0]
  ratio_y_range: [0.8,1.2]

Iso_pt_eta_bins:
  name: 'Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 && id_90_t && id_90_p'
  probe: 'iso_p < 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} < 0.15"
  y_range: [0.6,1.0]
  ratio_y_range: [0.8,1.2]

AIso_pt_bins_inc_eta:
  name: 'AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 && id_90_t && id_90_p'
  probe: 'iso_p >= 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} > 0.15"
  y_range: [0.6,1.0]
  ratio_y_range: [0.8,1.2]

AIso_pt_eta_bins:
  name: 'AIso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 && id_90_t && id_90_p'
  probe: 'iso_p >= 0.15 '
  binvar_x: 'pt_p'
  bins_x: [10., 15., 20., 24., 26., 28., 30., 32., 34., 36., 38., 40., 45., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} > 0.15"
  y_range: [0.6,1.0]
  ratio_y_range: [0.8,1.2]

Trg_Iso_pt_bins_inc_eta:
  name: 'Trg_Iso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: 'trg_p_Ele25eta2p1WPTight'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele25"
  y_range: [0.0,1.0]
  ratio_y_range: [0.1,1.9]

Trg_Iso_pt_eta_bins:
  name: 'Trg_Iso_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 &&  id_90_t && iso_p < 0.15 && id_90_p'
  probe: 'trg_p_Ele25eta2p1WPTight'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0.0, 1.0, 1.4442, 1.56, 2.1, 2.5]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele25"
  y_range: [0.0,1.0]
  ratio_y_range: [0.1,1.9]

Trg_AIso_pt_bins_inc_eta:
  name: 'Trg_AIso_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Ele25eta2p1WPTight && pt_t >= 26 &&  id_90_t && iso_p >= 0.15 && id_90_p'
  probe: 'trg_p_Ele25eta2p1WPTight'
  binvar_x: 'pt_p'
  bins_x: [10., 20., 25., 26., 27., 28., 29., 30., 31, 32., 33., 34., 35., 36., 37., 38., 39., 40., 42., 44., 46., 48., 50., 100., 200., 1000.]
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Ele25, Iso_{rel} > 0.15"
  y_range: [0.0,1.0]
  ratio_y_range: [0.1,1.9]