ID_pt_bins_inc_eta:
  # Settings for histogram creation
  name: 'ID_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23'
  probe: 'id_p'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Medium ID"
  y_range: [0.8,1.0]
  ratio_y_range: [0.8,1.2]

ID_pt_eta_bins:
  name: 'ID_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23'
  probe: 'id_p'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000] 
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Medium ID"
  y_range: [0.8,1.0]
  ratio_y_range: [0.8,1.2]

EmbID_pt_bins_inc_eta:
  # Settings for histogram creation
  name: 'EmbID_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23'
  probe: 'id_emb_p'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000] 
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Embedding ID"
  y_range: [0.8,1.0]
  ratio_y_range: [0.8,1.2]

EmbID_pt_eta_bins:
  name: 'EmbID_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23'
  probe: 'id_emb_p'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000]  
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Embedding ID"
  y_range: [0.8,1.0]
  ratio_y_range: [0.8,1.2]

Trg8_pt_eta_bins:
  name: 'Trg8_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23 && id_emb_p && pt_p>8.0'
  probe: 'trg_p_Mu17Mu8 || trg_p_Mu17TrkMu8'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000] 
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Mu22"
  y_range: [0.0,1.0]
  ratio_y_range: [0.8,1.2]

Trg8_pt_bins_inc_eta:
  name: 'Trg8_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23 && id_emb_p && pt_p>8.0'
  probe: 'trg_p_Mu17Mu8 || trg_p_Mu17TrkMu8'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Mu22"
  y_range: [0.0,1.0]
  ratio_y_range: [0.8,1.2]

Trg17_pt_eta_bins:
  name: 'Trg17_pt_eta_bins'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23 && id_emb_p && pt_p>17.0'
  probe: 'trg_p_Mu17Mu8 || trg_p_Mu17TrkMu8'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000] 
  binvar_y: 'abs(eta_p)'
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Mu22"
  y_range: [0.0,1.0]
  ratio_y_range: [0.8,1.2]

Trg17_pt_bins_inc_eta:
  name: 'Trg17_pt_bins_inc_eta'
  var: 'm_ll(50,65,115)'
  tag: 'trg_t_Mu22 && pt_t > 23 && id_emb_p && pt_p>17.0'
  probe: 'trg_p_Mu17Mu8 || trg_p_Mu17TrkMu8'
  binvar_x: 'pt_p'
  bins_x: [10,12,14,16,18,20,22,24,26,28,31,34,37,40,45,50,60,70,100,1000]
  binvar_y: 'eta_p'
  bins_y: [-2.4, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Trg Mu22"
  y_range: [0.0,1.0]
  ratio_y_range: [0.8,1.2]
