ID_pt_eta_bins:
  name: "ID_pt_eta_bins"
  var: "m_vis(50,65,115)"
  tag:  (
          (iso_tag < 0.15) && 
          ((fsr_photon_veto_tag < 0.5) && (fsr_photon_veto_probe < 0.5)) && 
          (id_medium_tag) && 
          (
            (trg_IsoMu22_tag) || 
            (trg_IsoTkMu22_tag) || 
            (trg_IsoMu22_eta2p1_tag) || 
            (trg_IsoTkMu22_eta2p1_tag)
          ) && 
          (pt_tag > 23.0) &&
          ((q_1 + q_2) == 0) &&
          (abs(dz_tag) < 0.2) &&
          (abs(dxy_tag) < 0.045)
        )
  probe:  (id_medium_probe)
  binvar_x: "pt_probe"
  bins_x:
    [
      10.,
      15.,
      20.,
      22.,
      24.,
      26.,
      28.,
      30.,
      32.,
      34.,
      36.,
      38.,
      40.,
      45.,
      50.,
      60.,
      80.,
      100.,
      200.,
    ]
  binvar_y: "abs(eta_probe)"
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Medium Muon ID"
  y_range: [0.7, 1.05]
  ratio_y_range: [0.7, 1.1]
  info: "Scale factor for the medium muon ID (binned in eta). Scale factor is provided for Embedding (emb) and Simulation (mc)"
  header: "Scale factor for the medium muon ID (binned in eta)"

Iso_pt_eta_bins:
  name: "Iso_pt_eta_bins"
  var: "m_vis(50,65,115)"
  tag:  (
          (iso_tag < 0.15) && 
          ((fsr_photon_veto_tag < 0.5) && (fsr_photon_veto_probe < 0.5)) && 
          ((id_medium_tag) && (id_medium_probe)) && 
          (
            (trg_IsoMu22_tag) || 
            (trg_IsoTkMu22_tag) || 
            (trg_IsoMu22_eta2p1_tag) || 
            (trg_IsoTkMu22_eta2p1_tag)
          ) && 
          (pt_tag > 23.0) &&
          ((q_1 + q_2) == 0) &&
          (abs(dz_tag) < 0.2) &&
          (abs(dxy_tag) < 0.045)
        )
  probe:  (iso_probe < 0.15)
  binvar_x: "pt_probe"
  bins_x:
    [
      10.,
      15.,
      20.,
      22.,
      24.,
      26.,
      28.,
      30.,
      32.,
      34.,
      36.,
      38.,
      40.,
      45.,
      50.,
      60.,
      80.,
      100.,
      200.,
    ]
  binvar_y: "abs(eta_probe)"
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{#mu,rel} < 0.15"
  y_range: [0.6, 1.0]
  ratio_y_range: [0.8, 1.2]
  info: "Scale factor for the muon isolation iso_mu < 0.15 (binned in eta). Scale factor is provided for Embedding (emb) and Simulation (mc)"
  header: "Scale factor for the muon isolation iso_mu < 0.15 (binned in eta)"

AIso1_pt_eta_bins:
  name: "AIso1_pt_eta_bins"
  var: "m_vis(50,65,115)"
  tag:  (
          (iso_tag < 0.15) && 
          ((fsr_photon_veto_tag < 0.5) && (fsr_photon_veto_probe < 0.5)) && 
          ((id_medium_tag) && (id_medium_probe)) && 
          (
            (trg_IsoMu22_tag) || 
            (trg_IsoTkMu22_tag) || 
            (trg_IsoMu22_eta2p1_tag) || 
            (trg_IsoTkMu22_eta2p1_tag)
          ) && 
          (pt_tag > 23.0) &&
          ((q_1 + q_2) == 0) &&
          (abs(dz_tag) < 0.2) &&
          (abs(dxy_tag) < 0.045)
        )
  probe:  ((iso_probe >= 0.15) && (iso_probe < 0.25))
  binvar_x: "pt_probe"
  bins_x:
    [
      10.,
      15.,
      20.,
      22.,
      24.,
      26.,
      28.,
      30.,
      32.,
      34.,
      36.,
      38.,
      40.,
      45.,
      50.,
      60.,
      80.,
      100.,
      200.,
      1000.,
    ]
  binvar_y: "abs(eta_probe)"
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} #in [0.15,0.25]"
  y_range: [0.0, 1.0]
  ratio_y_range: [0.6, 1.4]
  info: "Scale factor for the muon isolation 0.15 < iso_mu < 0.25 (binned in eta). Scale factor is provided for Embedding (emb) and Simulation (mc)"
  header: "Scale factor for the muon isolation 0.15 < iso_mu < 0.25 (binned in eta)"

AIso2_pt_eta_bins:
  name: "AIso2_pt_eta_bins"
  var: "m_vis(50,65,115)"
  tag:  (
          (iso_tag < 0.15) && 
          ((fsr_photon_veto_tag < 0.5) && (fsr_photon_veto_probe < 0.5)) && 
          ((id_medium_tag) && (id_medium_probe)) && 
          (
            (trg_IsoMu22_tag) || 
            (trg_IsoTkMu22_tag) || 
            (trg_IsoMu22_eta2p1_tag) || 
            (trg_IsoTkMu22_eta2p1_tag)
          ) && 
          (pt_tag > 23.0) &&
          ((q_1 + q_2) == 0) &&
          (abs(dz_tag) < 0.2) &&
          (abs(dxy_tag) < 0.045)
        )
  probe:  ((iso_probe >= 0.25) && (iso_probe < 0.50))
  binvar_x: "pt_probe"
  bins_x:
    [
      10.,
      15.,
      20.,
      22.,
      24.,
      26.,
      28.,
      30.,
      32.,
      34.,
      36.,
      38.,
      40.,
      45.,
      50.,
      60.,
      80.,
      100.,
      200.,
      1000.,
    ]
  binvar_y: "abs(eta_probe)"
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} #in [0.25,0.50]"
  y_range: [0.0, 1.0]
  ratio_y_range: [0.6, 1.4]
  info: "Scale factor for the muon isolation 0.25 < iso_mu < 0.2 (binned in eta). Scale factor is provided for Embedding (emb) and Simulation (mc)"
  header: "Scale factor for the muon isolation 0.25 < iso_mu < 0.2 (binned in eta)"

AIso3_pt_eta_bins:
  name: "AIso3_pt_eta_bins"
  var: "m_vis(50,65,115)"
  tag:  (
          (iso_tag < 0.15) && 
          ((fsr_photon_veto_tag < 0.5) && (fsr_photon_veto_probe < 0.5)) && 
          ((id_medium_tag) && (id_medium_probe)) && 
          (
            (trg_IsoMu22_tag) || 
            (trg_IsoTkMu22_tag) || 
            (trg_IsoMu22_eta2p1_tag) || 
            (trg_IsoTkMu22_eta2p1_tag)
          ) && 
          (pt_tag > 23.0) &&
          ((q_1 + q_2) == 0) &&
          (abs(dz_tag) < 0.2) &&
          (abs(dxy_tag) < 0.045)
        )
  probe:  ((iso_probe >= 0.15) && (iso_probe < 0.50))
  binvar_x: "pt_probe"
  bins_x:
    [
      10.,
      15.,
      20.,
      22.,
      24.,
      26.,
      28.,
      30.,
      32.,
      34.,
      36.,
      38.,
      40.,
      45.,
      50.,
      60.,
      80.,
      100.,
      200.,
      1000.,
    ]
  binvar_y: "abs(eta_probe)"
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "Exponential"
  SIG: "DoubleVCorr"
  # Settings for plotting
  TITLE: "Iso_{rel} #in [0.15,0.50]"
  y_range: [0.0, 1.0]
  ratio_y_range: [0.6, 1.4]
  info: "Scale factor for the muon isolation 0.15 < iso_mu < 0.5 (binned in eta). Scale factor is provided for Embedding (emb) and Simulation (mc)"
  header: "Scale factor for the muon isolation 0.15 < iso_mu < 0.5 (binned in eta)"

Trg_pt_eta_bins:
  name: "Trg_pt_eta_bins"
  var: "m_vis(50,65,115)"
  tag:  (
          ((iso_tag < 0.15) && (iso_probe < 0.15)) && 
          ((fsr_photon_veto_tag < 0.5) && (fsr_photon_veto_probe < 0.5)) && 
          ((id_medium_tag) && (id_medium_probe)) && 
          (
            (trg_IsoMu22_tag) || 
            (trg_IsoTkMu22_tag) || 
            (trg_IsoMu22_eta2p1_tag) || 
            (trg_IsoTkMu22_eta2p1_tag)
          ) && 
          (pt_tag > 23.0) &&
          ((q_1 + q_2) == 0) &&
          (abs(dz_tag) < 0.2) &&
          (abs(dxy_tag) < 0.045)
        )
  probe:  (
            (trg_IsoMu22_probe) || 
            (trg_IsoTkMu22_probe) || 
            (trg_IsoMu22_eta2p1_probe) || 
            (trg_IsoTkMu22_eta2p1_probe)
          )
  binvar_x: "pt_probe"
  bins_x:
    [
      10.,
      15.,
      20.,
      21.,
      22.,
      23.,
      24.,
      25.,
      26.,
      27.,
      28.,
      29.,
      30.,
      31,
      32.,
      33.,
      34.,
      35.,
      36.,
      38.,
      40.,
      45.,
      50.,
      60.,
      80.,
      100.,
      200.,
    ]
  binvar_y: "abs(eta_probe)"
  bins_y: [0, 0.9, 1.2, 2.1, 2.4]
  # Settings for fits
  BKG: "CMSShape"
  SIG: "DoubleVPartcorr"
  # Settings for plotting
  TITLE: "Single Muon Trigger"
  y_range: [0.0, 1.1]
  ratio_y_range: [0.8, 1.2]
  info: "Scale factor for the muon trigger (IsoMu22|IsoTkMu22|IsoMu22_eta2p1|IsoTkMu22_eta2p1) in isolated region mu_iso < 0.15 (inclusive in eta). Scale factor is provided for Embedding (emb) and Simulation (mc)"
  header: "Scale factor for the muon trigger (IsoMu22|IsoTkMu22|IsoMu22_eta2p1|IsoTkMu22_eta2p1) in isolated region mu_iso < 0.15 (inclusive in eta)"
